# Generated by Django 3.0.3 on 2020-02-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200224_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='subtotal',
        ),
    ]
